name: 07 - Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

env:
  MY_VAR_WITH_DEFAULT: ${{ inputs.debug && 'DEBUG with assigned value' || 'default value' }}
on: 
  # push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start-up'
        # if: ${{ inputs.debug }}
        if: inputs.debug
        run: |
          echo "Triggered by ${{ github.event_name}}"
          echo "Branch ${{ github.ref }}"
          echo "Commit sha: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: '[debug] Print when triggered from the main'
        # if: ${{ inputs.debug && github.ref == 'refs/heads/main'}}
        if: inputs.debug && github.ref == 'refs/heads/main'
        run: echo "I was triggered from main"
      - name: Greeting
        run: |
          echo "Hello world"
          echo "MY_VAR_WITH_DEFAULT: ${{env.MY_VAR_WITH_DEFAULT }}"

