name: 17 - 1 - Custom actions - composite
run-name: 17 - 1 - Custom actions - composite | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: Which environment to target for dependency installation
        type: choice
        options:
          - dev
          - prod

env:
  working-directory: 17-custom-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      # Ojo, primero debo hacer checkout
      - uses: actions/checkout@v4
      - name: Setup Node and NPM dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 22.x
          working-dir: ${{ env.working-directory }}
          target-env: ${{ inputs.target-env }}
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
