name: 17 - 2 - Custom actions - JS
run-name: 17 - 2 - Custom actions - JS

on:
  workflow_dispatch:

jobs:
  dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
